### ISSUE TITLE
[FEAT.] Add a Pull Request template

### ISSUE THREAD

**Issue by FahimFBA** [FahimFBA/assist-me#13]
**Is your feature request related to a problem? Please describe.**
This project is missing a Pull Request template.

**Describe the solution you'd like**
I want to work on this issue and create a PR template.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anirudhnayak27** [comment]
can i work on that?

**Comment by FahimFBA** [comment]
> can i work on that?

Sorry, this task is already assigned. 😅
You can check for other unassigned tasks. I hope you will get some good issues to work on! 👍
