### ISSUE TITLE
[FEAT.] add tailwind css to the project

### ISSUE THREAD

**Issue by JoyShaheb** [FahimFBA/assist-me#16]
add tailwind css configuration to the project following the documentation from the official website for vitejs react

**Comment by priyanshtiwari001** [comment]
Hi can you please assign this issue to me.

**Comment by JoyShaheb** [comment]
@priyanshtiwari001  sure go for it, make sure that you exactly follow the docs for vitejs on tailwind css official website

**Comment by FahimFBA** [comment]
It has already been implemented on a different PR.
