### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by FahimFBA** [FahimFBA/assist-me#2]
Could you add some relevant issue templates? 

For now, add the below 3 types of issue templates:

1. Bug
2. Feature
3. Others

**Comment by VividhPandey003** [comment]
sure, could you please assign this issue to me under hacktoberfest

**Comment by FahimFBA** [comment]
> sure, could you please assign this issue to me under hacktoberfest

Sure! Go ahead.

**Comment by VividhPandey003** [comment]
@FahimFBA Could you please review my Pull Request. I have made the required changes. 
Thanks

**Comment by FahimFBA** [comment]
This issue has been resolved through PR #8
