### ISSUE TITLE
[BUG] website title

### ISSUE THREAD

**Issue by FahimFBA** [FahimFBA/assist-me#27]
**Describe the bug**
The current title is showing `Vite + React + TS`. 

**Expected behavior**
It should be `AssistMe`.

**Comment by swatichauhan814** [comment]
Hi, 
I would like to work on this issue. Can you please assign me ?

**Comment by FahimFBA** [comment]
> Hi, I would like to work on this issue. Can you please assign me ?

Thank you for your interest, but this issue has already been resolved and waiting for review in the pull request #28 .
