### ISSUE TITLE
[BUG] Rating section doesn't work properly on home page

### ISSUE THREAD

**Issue by JoyShaheb** [FahimFBA/assist-me#35]
Description of problem
![image](https://github.com/FahimFBA/assist-me/assets/61899866/2f9b92bc-4776-4743-bd8d-1671f3d7cc8d)

**Comment by harshvyas-22** [comment]
i would love to contribute in this kindly assign to me

**Comment by JoyShaheb** [comment]
@harshvyas-22 sure go for it
