### ISSUE TITLE
[FEAT.] Add a way to implement reset and forgot password

### ISSUE THREAD

**Issue by JoyShaheb** [FahimFBA/assist-me#46]
The users should be able to reset and forgot password for their account

**Comment by inclinedadarsh** [comment]
Heyy there @JoyShaheb 
I would like to work on this, can you please assign this to me?

Also, I had few questions.
- I already see pages for Reset Password and Forgot Password, but they're include. Are they supposed to be complete after completion of this issue?
- What service are you using to send emails?

**Comment by JoyShaheb** [comment]
@inclinedadarsh  its very easy, we are using firebase reset password feature. all you have to do is implement the firebase send email code on the redux toolkit query, and once you request a reset email, you should get a mail where you can click on the link to reset the password. might take 1-2 hours to finish, you interested ?

**Comment by inclinedadarsh** [comment]
Heyy! 
I have never worked with Firebase, so I won't be able to do this one.

If someone else wants, they can take this issue.

**Comment by FahimFBA** [comment]
It has already been implemented on a different PR.
