### ISSUE TITLE
[BUG] Navbar not hiding when scrolled down

### ISSUE THREAD

**Issue by JoyShaheb** [FahimFBA/assist-me#47]
The navbar should hide and show itself when user scrolls down or up. this is very simple to accomplish. use the library called react-headroom, follow the docs and then done

* Resource Link : https://www.npmjs.com/package/react-headroom

**Comment by JoyShaheb** [comment]
@ankur-dahiya you can do this

**Comment by ankur-dahiya** [comment]
on it

**Comment by 08Uzair** [comment]
Please assign this to me i will do this in 1-2 hrs

**Comment by ankur-dahiya** [comment]
@08Uzair i will submit it today kindly find yourself another issue

**Comment by ankur-dahiya** [comment]
@JoyShaheb can i get some help with the environment variables(for setting up local environment)?
also getting the error 
1:28:30 pm [vite] Failed to load source map for /src/styles/plugin.css.
1:28:30 pm [vite] Failed to load source map for /src/styles/style.css.

**Comment by JoyShaheb** [comment]
@ankur-dahiya  for environment variables, login to firebase, create a simple project and they should provide the env variables out of the box, copy them and put it on .env files.  you should copy varaible names from .sample.env file

**Comment by ankur-dahiya** [comment]
@JoyShaheb please check and merge it with hacktoberfest-accepted tag thx again for letting me work on this....if there's any issue please letme know

**Comment by 08Uzair** [comment]
Please assign this to me i will do my work in 1-2 hrs

**Comment by ankur-dahiya** [comment]
@08Uzair its already done my friend
