### ISSUE TITLE
[BUG] Unwanted horizontal margins in the UI

### ISSUE THREAD

**Issue by IsratIJK** [FahimFBA/assist-me#49]
**Describe the bug**
There are some unwanted horizontal lines in the UI. Check the image below. 
![image](https://github.com/FahimFBA/assist-me/assets/74541103/58e8f1b7-4031-4c56-b312-d20782bebc53)

**To Reproduce**
1. Go to the website
2. Scroll down until you get the horizontal lines as shown in the image
3. See error

**Expected behavior**
There shouldn't be any horizontal lines and they should be in a block.

**Screenshots**
![image](https://github.com/FahimFBA/assist-me/assets/74541103/28c7bc00-580b-4e65-a8bf-6013f39b583c)

**Comment by harsh31dangi** [comment]
Hi, I would like to work on this issue. Can I?
