### ISSUE TITLE
add: react router dom latest version

### ISSUE THREAD

**Issue by JoyShaheb** [FahimFBA/assist-me#7]
Add React router dom and add following pages
* Home
* Login
* Signup
* ResetPassword
* ForgotPassword
* Dashboard

**Comment by priyanshtiwari001** [comment]
Hi , can you please assign this issue to me and please explain me the issue.

**Comment by FahimFBA** [comment]
> Hi , can you please assign this issue to me and please explain me the issue.

Sorry, this issue has already been assigned to someone else. Please find another unassigned issue. I hope that helps you. 😃
