### ISSUE TITLE
[BUG] Label workflow doesn't work

### ISSUE THREAD

**Issue by FahimFBA** [FahimFBA/assist-me#73]
**Describe the bug**
The workflow for giving labels is not working.

![image](https://github.com/FahimFBA/assist-me/assets/64195132/d252941c-3ab4-450a-aab4-b6c3b4ef5805)

**Comment by duongyennhi** [comment]
Hello. Can I help you? May you assign it to me?

**Comment by FahimFBA** [comment]
> Hello. Can I help you? May you assign it to me?

Sure! But the Hacktoberfest is already over, if you are only thinking about the Hacktoberfest.

**Comment by FahimFBA** [comment]
Hello @duongyennhi 
You haven't responded yet. I am unassigning you thinking that you are not available anymore for this issue.

**Comment by FahimFBA** [comment]
Simply remove the label workflow for now. Assigning myself for this now.
